### ISSUE TITLE
Web of Things (WoT) Model in Ditto

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/ditto#1034]
Hi all,
I would like to open up the discussion of using WoT to describe a feature/thing.
Vorto was the go-to solution to describe a thing but it looks like this will be discontinued. Therefore, we are looking for another solution to describe our models. WoT, more specifically the "Thing Model", has been mentioned several times in the gitter chat and looks like a good fit.
We would like to get everyone on the same page concerning this so we can easily use a possible future integration between Ditto and WoT. 
The ultimate result of this issue/discussion IMO would be a best practice article in Ditto documentation which will be a guideline for a future integration. In order to have that, we should agree upon this best practice.
WDYT?

**Comment by thjaeckle** [comment]
I have a close watch to WoT "Thing Model" currently documented here (but also in active "development" of the spec):
https://w3c.github.io/wot-thing-description/#thing-model

WoT quote:
> "This paradigm can be compared with abstract class or interface definition (~Thing Model) in object-oriented programming to create objects (~Thing Descriptions)."

A WoT "Thing Model":
> [...] mainly describes interaction affordances such as the [Properties](https://w3c.github.io/wot-thing-description/#dfn-property), [Actions](https://w3c.github.io/wot-thing-description/#dfn-action), and [Events](https://w3c.github.io/wot-thing-description/#dfn-event) and common metadata.

A Ditto Thing is unfortunately not a good fit for the WoT "Thing Model" - because a Thing in Ditto may consist of several features, all of which can follow "interface definitions".
However I think that a Ditto "Feature" (part of a Thing) is the perfect match for being backed by a WoT "Thing Model".

| WoT Thing Model concept | Ditto concept |
| ---                                       | ---                   |
| [Properties](https://w3c.github.io/wot-thing-description/#dfn-property) | Feature properties |
| [Actions](https://w3c.github.io/wot-thing-description/#dfn-action) | Feature "inbox" (TO the thing) messages |
| [Events](https://w3c.github.io/wot-thing-description/#dfn-event) | Feature "outbox" (FROM the thing) messages |

The [Feature definition](https://www.eclipse.org/ditto/basic-feature.html#feature-definition) is a Json Array of String, currently limited to the form:
* `<namespace>:<name>:<version>`

Which is obviously targeted to Vorto models.
I think we could relax this restriction and also accept URIs ... that way you could define URIs to WoT "Thing Models" (JSON-LD files available via HTTP, e.g. hosted by a GitHub repo).

The [Thing level definition](https://www.eclipse.org/ditto/basic-thing.html#definition) currently does not have a match to a WoT concept.
It could (to think about!) make sense to apply the thing level definition, also accepting a WoT "Thing Model" to the Thing attributes + to the messages (actions/events in WoT speak) you can directly send/receive from a Thing.

What I really like about the WoT "Thing Model" is the closeness to "JSON Schema" - IMO that would be the best way to do a validation of JSON data, e.g. for feature properties or messages.

**Comment by tuve** [comment]
> Vorto was the go-to solution to describe a thing but it looks like this will be discontinued.

I can't find any information on vorto is going to be discontinued, in fact version 1.0.0 vas released last November? Or is it the ditto plugin? Anyone from the Vorto project who can comment on this? @aedelmann @mena-bosch @t-gauss

**Comment by kolotu** [comment]
@tuve Vorto is not being explicitly discontinued, but there is currently no further development (or maintenance) planned within the project. Also the Vorto repository that you can currently find here https://vorto.eclipseprojects.io/ will be shut down in July. You can find more detailed information on the Gitter channel eclipse/vorto.

**Comment by thjaeckle** [comment]
Started a discussion at https://github.com/w3c/wot-thing-description/issues/1177 for the currently (in my opinion) missing replacement for Vorto "InformationModel" being used in the Ditto Thing toplevel "definition".

If anyone wants to join into that discussion, please go ahead and do so :)

In the meantime another potential OpenSource option did arise for modeling structure and semantics: [Open Manufacturing Platform BAMM](https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model).
