### ISSUE TITLE
Documentation of merge effect could be improved

### ISSUE THREAD

**Issue by inno-steffg** [eclipse/ditto#1387]
Dear Ditto Team,

All the documentation and especially the examples around the effect of a merge command miss the actual part, how the content of the  thing JSON has changed from previous state to the state after execution of the merge command. Even more so, as the merge should leave sibling properties (those not in its value section) unchanged, what makes the merge command so different from the create/update command.

**Comment by thjaeckle** [comment]
@inno-steffg the [merge specification docs](https://www.eclipse.org/ditto/protocol-specification-things-merge.html) state:
> For all merge commands the value field is provided in [JSON merge patch](https://tools.ietf.org/html/rfc7396) format.

So instead of copying the documentation of the RFC 7396, we link to the RFC which describes exactly the effect of a "merge".

For your question about whether the change event contains only the original merge request or the complete state:
It only contains the field(s) contained in the merge and their values - if the complete state of the thing or of certain features is required when subscribing for change events, [enrichment via "extraFields"](https://www.eclipse.org/ditto/basic-enrichment.html) can be configured when subscribing for (merge) events.
