### ISSUE TITLE
Conditioning policies fruitfulness in Multi-Company architecture

### ISSUE THREAD

**Issue by RaiBnod** [eclipse/ditto#251]
- **Scenario:**
  I have a web app, which can create multiple companies and those multiple companies have their own users with multiple roles, called Admin, Manager, User etc... 

- **Problem:**
  When I create a fresh company '**company1**' on my web app, it should able to create ditto users like '**ditto-compay1-admin**', '**ditto-company1-manager**', '**ditto-company1-user**' etc... and create a policy to bind user on its limits. But unfortunately, it seems like we have no REST API to add/update/delete the user and user creation is limited to a file **'nginx.htpasswd'**. If that is the case, we can't achieve the dynamic behavior of policies for such scenarios. We always need to go on the nginx file and need to add/edit/delete the content and need to restart nginx and that will be repetitive.

Am I missing something over here that we could do its alternative with the current ditto support or this case is never handled/yet to be handled?

**Comment by RaiBnod** [comment]
In documentation we can find:

**Authentication**
User authentication at the HTTP API

A user who calls the HTTP API can be authenticated using two mechanisms:

- HTTP BASIC Authentication by providing username and password of users managed within for example nginx acting as reverse proxy.
- A JWT issued by Google or other OpenID Connect providers.

But not much documentation on second point.

**Comment by thjaeckle** [comment]
Hi.

Ditto does not include a user management and Ditto does not provide authentication - that's why we have **as an example** the nginx-based authentication via BasicAuth.
If you need authentication (and a user management), you should combine it with another tool/project providing that. [Keycloak](https://www.keycloak.org) might be interesting for you.

Another alternative to include any other authentication provider you already have (e.g. ActiveDirectory) is to implement your own implementation of interface [AuthenticationProvider](https://github.com/eclipse/ditto/blob/master/services/gateway/endpoints/src/main/java/org/eclipse/ditto/services/gateway/endpoints/directives/auth/AuthenticationProvider.java). A good example/starting point could be the [DummyAuthenticationProvider](https://github.com/eclipse/ditto/blob/master/services/gateway/endpoints/src/main/java/org/eclipse/ditto/services/gateway/endpoints/directives/auth/dummy/DummyAuthenticationProvider.java) which simply extracts user credentials from a header field `x-ditto-dummy-auth` - that mechanism is used in our example nginx based authentication. The nginx sets this header when a user was authenticated, see example [nginx.conf](https://github.com/eclipse/ditto/blob/master/deployment/docker/nginx.conf#L41).

Towards the JWT based authentication (e.g. via Google) - simply set the JWT `id_token` of a authenicated Google user as `Authorization Bearer` http header. This is default OAuth2.0.
Ditto supports out-of-the-box Google OAuth2.0 provider, see here in the code:
https://github.com/eclipse/ditto/blob/master/services/gateway/endpoints/src/main/java/org/eclipse/ditto/services/gateway/endpoints/directives/auth/DittoGatewayAuthenticationDirectiveFactory.java#L91

You can of course also add other OAuth2.0 providers there (e.g. your own Keycloak if you decide to use that).

Sorry, this is no free lunch - you have to implement something for getting it done.
