### ISSUE TITLE
Missing developer documentation

### ISSUE THREAD

**Issue by onurakdemir** [eclipse/ditto#354]
Hello ditto team,

I want to work on some issues about ditto but I couldn't find a development document. Do you have any best practices for development?

Thank you.

**Comment by thjaeckle** [comment]
Hi Onur.
Indeed, we do not yet have a developer documentation showing how to debug, etc.

What we do in development is simply to start all services right in the IDE (e.g. we use IntelliJ):
* [PoliciesService](https://github.com/eclipse/ditto/blob/master/services/policies/starter/src/main/java/org/eclipse/ditto/services/policies/starter/PoliciesService.java)
* [ThingsService](https://github.com/eclipse/ditto/blob/master/services/things/starter/src/main/java/org/eclipse/ditto/services/things/starter/ThingsService.java)
* ConciergeService
* GatewayService
* ConnectivityService
* SearchService

Important is to **start the `PoliciesService` first** as this done is used as "bootstrapper" during development.

By simply starting them without any arguments, the `*-dev.conf` files are loaded, e.g. [policies-dev.conf](https://github.com/eclipse/ditto/blob/master/services/policies/starter/src/main/resources/policies-dev.conf).
Those expect to find a MongoDB running on `localhost:27017`. That one can be started inside Docker or started natively on your machine.

The `GatewayService` opens a HTTP endpoint on `localhost:8080` but there is no nginx in front of that during development.
Simply set the HTTP header `x-ditto-dummy-auth` to the form `<prefix>:username` in order to work with different "pre-authenticated" users, e.g.: `x-ditto-dummy-auth=ditto:my-user`.

We will use this issue to track adding that information (and potentially more needed to develop/debug) to our README.md
