### ISSUE TITLE
Eclipse Ditto on Microsoft Azure

### ISSUE THREAD

**Issue by kaizimmerm** [eclipse/ditto#358]
Hi Ditto community,

I would like to get your feedback and potential interest on contributions in order to improve the experience with Eclipse Ditto on Microsoft Azure. I wrote a small proposal (see below) covering multiple aspects of the topic.

Let me know what you guys think,

Kai

## Overview

For an optimized [Eclipse Ditto™](https://www.eclipse.org/ditto/) experience on Microsoft Azure several aspects have to be considered:

- To deploy and host Ditto on Microsoft Azure.
- To integrate Ditto with applications hosted on Azure.
- Optionally to integrate Ditto with Azure IoT by supporting synchronization with [Azure IoT Device Twin](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins) state, e.g.
  - to combine Azure IoT's highly scalable connectivity features with the Ditto feature set.
  - and/or to  leverage Ditto as federation service for devices connected to Azure IoT and other connectivity layers.
  - and/or to integrate [Azure IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/about-iot-edge) with Ditto.

We propose to split the work necessary to allow the Ditto community to leverage these features into three work streams:

- Azure deployment support for Eclipse Ditto.
- Azure PaaS service integration guidance, support and verification.
- Rich collection of samples and references.

As mentioned; before we start digging into these we would like to collect your feedback. Pls keep in mind that this is more a set of ideas at this point and is not to be seen as a promise for contribution by us 😄 

## Proposed architecture

![Overview](https://user-images.githubusercontent.com/9153035/54420517-77671480-470a-11e9-8daa-9ae81fd8fd3d.png)

### Azure deployment support for Eclipse Ditto

- [Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/intro-kubernetes) deployment
  - [Azure Resource Manager (ARM)](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview) templates (i.e. infrastructure as code) for AKS including network setup.
    - Location proposal: `deployment/azure`
  - Helm templates:
    - Flexible k8s deployment that works for existing Ditto (e.g. Minikube) as well as other environments (like AKS).
    - Include optional setups (k8s ingress, TLS with Let’s Encrypt certs, etc.)
  - Include Azure key vault support (see https://github.com/Azure/kubernetes-keyvault-flexvol) including AAD service principal.
  - Provide [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines) reference to setup Ditto build pipeline including Azure Container Registry deployment for Docker images and Helm charts as well as automated AKS deployments.
- MongoDB persistence
  - Evaluate feasibility of [Azure CosmosDB](https://docs.microsoft.com/en-us/azure/cosmos-db/introduction) as alternative to MongoDB

### Azure PaaS service integration

- Application integration
  - Ditto "Target": Provide and test reference based on [Azure Event Hubs](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-about) (including its Kafka support) and Azure ServiceBus topics.
  - Ditto "Source": Provide and test reference based on [Azure Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview) queues.
    - To be discussed: is Ditto source expecting a topic or a queue for message consumption?
- Azure IoT Integration
  - Provide integration (service) to exchange data between [Azure IoT Hub](https://docs.microsoft.com/en-us/azure/iot-hub/about-iot-hub) with Ditto.
- Testing
  - Run automated integration tests.

### Collection of samples and references

- Guides/publishing
  - Provide complete deployment guide (to be discussed, Ditto website or Readme?)
    - Location proposal: `deployment/azure`
- References/samples
  - Spring Boot based sample apps that retrieves from and publishes messages into Ditto.
    - Sample 1: Receives messages based on Event Hubs Kafka support using Spring Cloud Stream.
    - Sample 2: Send messages to ditto based on Azure ServiceBus (SDK).
  - [Azure Stream Analytics](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-introduction) sample that analyses Ditto event stream.
 - Azure IoT Edge end-2-end integration sample.

**Comment by thjaeckle** [comment]
Hi Kai.

Sounds really good, we're happy to see that Microsoft has an interest in Ditto.
Your proposal is not that small at all - if we're planning on doing all that, Ditto on Azure almost could feel like a native service I guess :+1: 

### Deployment

I think it makes most sense to start with that, that should be straight forward.
What will be interesting is whether Ditto can use Azure CosmosDB as MongoDB drop-in replacement.

We are currently working on concepts on how to improve our search feature which currently still makes use of MongoDB "aggregation pipelines". That won't be the case in the future, so that Ditto doesn't require too fancy MongoDB features.

### PaaS service integration

#### Azure device twin

Interesting to see that the concepts of Ditto's twin and Azure's twin are not that far apart. Personally, I'm not a fan of synchronizing data (especially in "master"-"master" setups where data may be modified in any system), so we should clarify what the benefit of such a synchronization would be.

Could also lead into some problems as the Azure twin has more restrictions on how the twin JSON might look like (e.g. forbids using arrays and usage of some special characters in JSON key names, has stronger restrictions on max size of a twin JSON, etc.).

#### Using a Microsoft mechanism for providing authentication for Ditto

One additional integration could be added which might be covered by the "Azure key vault" you mentioned, but I'm not sure.

As Ditto only handles authorization based on already authenticated users/devices, etc. (we call that `authorizationSubject`), a way for providing authentication in front of Ditto would be great.
For the Ditto sandbox we currently simply use nginx with a `.htpasswd` file which provides authentication on HTTP and Websocket resources.

If a similar approach is not sufficient, we are currently working on #348 in order to simplify adding new authentication mechanisms.

### Samples

A deployment guide for Azure would be great, location to be clarified.

Samples could go to https://github.com/eclipse/ditto-examples where we don't need to do CQs for dependencies, so adding Spring Boot dependency hell there would be ok, although personally I'm a fan of simplicity and non-magically behaving applications ;)

----

Would be great to also get feedback of some of our users on that.
@onurakdemir @BobOntario @haijunjiang @kuzuilker @sergiomanso @s-kurauchi @saunakasansol94 @Gaurav047
Any thoughts on the proposal?

**Comment by yufei-cai** [comment]
Is this issue up to date? Any news?

**Comment by thjaeckle** [comment]
Now that Ditto added support for Azure's HMAC based singature based authentication (see [Blogpost](https://www.eclipse.org/ditto/2021-06-17-hmac-credentials.html)), the integration options of Ditto with Azure got a lot bigger.

I will close this issue now as there is FMPOV nothing still "open" or "to address".
