### ISSUE TITLE
Structure architecture by domain instead of technical structure

### ISSUE THREAD

**Issue by Yannic92** [eclipse/ditto#415]
Right now we have kind of a mixed architecture.

On top level we separate into:
- model
- services
- signals

below these three technical modules we separate into domain specific modules like
- policies
- things
- ...

for the services module it's even more weird.

* model
  * policies
  * ...
* services
  * policies
  * models
    * policies
  * ...
* ...

Wouldn't it be better to have the domain structure on top level and then structure the respective domains in their technical components?

**Comment by thjaeckle** [comment]
Hm, `json`, `model`, `protocol-adapter`, `signals` on top-level is not a technical module separation for me. Those are all modules which can be seen as API.
`services` however does not contain API (in the sense of Java API, of course there is API in form of HTTP API in there) which we would want to keep backward compatible.
Also, all sub-modules of `signals` share common dependencies which are defined in the `signals/pom.xml` - I think that would be harder to achieve when splitting on top-level for domains.

What benefits do you have in mind when changing the structure?
What is "better" then?

**Comment by Yannic92** [comment]
For `json` and `protocal-adapter` I'm with you. It's something that can stand alone and does not belong to any service.
For `signals` I'm only partially with you.
I thing something like [Command](https://github.com/eclipse/ditto/blob/master/signals/commands/base/src/main/java/org/eclipse/ditto/signals/commands/base/Command.java) should be specified in a separate module. I'm not sure if signal is the best name for this, but I don't want to discuss about naming.

What I would except is that each service of ditto provides all it needs as submodules. Right now the policies service is spread all over the repository.
This makes adding new services or removing/deprecating services more difficult as you have to search all over the repo for things that belong to the service.

This would also make the boundaries of modules more clear. For example why is ditto-model-enforces an API? Should this be used outside of the ditto service? For me this is part of the concierge.
We currently do enforcing for example in ThingSearch, too. Is this intended? Shouldn't be concierge the one service that is responsible for authorization?

Another module is ditto-model-base. There is for example an auth package which is for me an independent module: security.
This module security could contain all AuthenticationProviders and everything that is required for authentication and authorization.
To my understanding it then should be sufficient to include this module in the gateway (authentication) and in concierge (authorization). Maybe in connectivity too because its kind of an API Gateway aswell. But its not required in all services in my opinion.

So in one sentence what I think "is better then": I think this would lead to a less confusing architecture with less dependecies to other services, what will lead to more independent microservices with a clearly defined API per service in the end.

**Comment by thjaeckle** [comment]
> But why is it helpful to define the API for a service like policies in a module outside of the policies service module?

It's not only the API for service-internals, but also for the Ditto Protocol and the (soon) to be added Java-client. Therefore it is helpful to separate between API and service.
That's the main point of why `model` and `signals` is on top-level.

What we experienced before applying that structure (before the initial Ditto code contribution) is that modules had cyclic dependencies all over the place. With the current structure the following dependency hierarchy is defined:
```
module(s)  |  referenced by
utils      <- json, model, signals, protocol-adapter, services
json       <- model
model      <- signals
signals    <- protocol-adapter
utils, json, model, signals, protocol-adapter <- services
```
So anything in `model` isn't allowed to reference something in `signals`, `protocol-adapter` or `services`.
Anything in `signals` isn't allowed to reference something in `protocol-adapter` or `services`.
And so on..

> This makes adding new services or removing/deprecating services more difficult as you have to search all over the repo for things that belong to the service.

Yes, but it also adds the required structure in order not to completely mess up dependencies.

>  For example why is ditto-model-enforces an API? Should this be used outside of the ditto service?
Because it also can be used as API, e.g. retrieve the policy from the backend and enforce the policy locally before talking to the service.

By having the enforcement as module the complete policy enforcement could be used standalone from the Ditto backend.

> We currently do enforcing for example in ThingSearch, too. Is this intended?

ThingSearch does enforcement on database query level, this is intended, yes. I don't think that it does the same as concierge, it may however need the same information from policies.

> Another module is ditto-model-base. There is for example an auth package which is for me an independent module: security.

Sure, that's a good idea.<br/>
As this would be used in 3 of 6 Ditto services I would also see that as a module built for re-use, but probably not in `models` but in a submodule of `services`.

> I think this would lead to a less confusing architecture with less dependecies to other services, what will lead to more independent microservices with a clearly defined API per service in the end.

I think it's important to define the API of the microservices (which currently is basically JSON commands, responses and events) as separate `model` and really treat those as API. With that approach we seldom had issues with breaking the API and/or JSON format in the past. I'm not convinced that this will be better when we move the models closer to the service implementation.

I agree that we should avoid inter-service dependencies - if services need common functionality, we should extract a new commonly used module.

I however don't see that we have a confusing architecture (at least not on modules level ;) ). Maybe it would help to have a picture in place?

As such a discussion is right to be done before a 1.0 release we should have it now, yes. Could you draw a diagram of how you would "cut" the modules architecture including inter-module dependencies?
I think that would help in seeing if that reduces complexity or not.

**Comment by thjaeckle** [comment]
That is the current "dependency matrix" (generated by IntelliJ) showing that at least we don't have any cycles in it :) and the modules at the bottom are used by the most other modules.
![image](https://user-images.githubusercontent.com/1331526/58460579-435a9780-812e-11e9-89cd-a9b82231cc95.png)

**Comment by Yannic92** [comment]
Thank you for the detailed feeback. I will provide such a diagram the next days.

**Comment by thjaeckle** [comment]
That diagram probably doesn't help (all ditto modules with their dependencies to each other), hotspots however can be seen :wink: 
![dependency-graph](https://user-images.githubusercontent.com/1331526/58462721-bebe4800-8132-11e9-98a3-58ee33bb79c0.png)

Gathered by running:
```
mvn com.github.ferstl:depgraph-maven-plugin:aggregate -Dscope=runtime -DcreateImage=true -DreduceEdges=false "-Dincludes=org.eclipse.ditto*:*" "-Dexcludes=org.eclipse.ditto:ditto-services-legal*:*"
```

**Comment by Yannic92** [comment]
Maybe I can reduce the number of modules and/or services. We'll see :) I'll investigate this.

> What we experienced before applying that structure (before the initial Ditto code contribution) is that modules had cyclic dependencies all over the place.

This could be an indicator that services are too tightly coupled and should not be to different services.

**Comment by thjaeckle** [comment]
This was done as part of Ditto 2.0
Thx again @Yannic92 for pulling that off 👍
