### ISSUE TITLE
JSON Policy Structure Proposed Revisions

### ISSUE THREAD

**Issue by dlouiscastillo** [eclipse/ditto#461]
In working with the Policies Collection, I found the JSON structure to not feel natural and inconsistent with all of the other JSON document types.

Rather than use key(name)/value pairs, it uses the meaningful data as the key name making it difficult to parse with standard packages such as JMESPath and JSONata.

For example, rather than use a keyname of subjectId with a value of the actual subject data, it uses the subjectId as the keyname and it's type as the value. 

Another example, is used in all three resources Thing, Policy and Message where the path is used as the keyname and the permissions as the value.  

In both of the cases listed, you can't use Javascript dot syntax to Get or Set the data. 

Another suggestion is to use arrays of objects for entries, subjects, policy, thing and message enabling the submission of multiple entries each with a different path for instance.

I make these suggestions only with the intention of reducing unnecessary friction for the developer and playing well in the larger ecosystem.

I've included a proposed sample document for review.

David 

[ThingPolicyProposal.txt](https://github.com/eclipse/ditto/files/3457195/ThingPolicyProposal.txt)

**Comment by thjaeckle** [comment]
Hi there.
Thanks for your interest in this project and feedback on such a crucial feature of Ditto.

When we designed the JSON format we decided on purpose to only include arrays at the "leaves" (e.g. for `grant` and `revoke` fields containing arbitrary strings of "permissions").
The main reason is that parts of the policy JSON document may be updated/queried partially via the HTTP API, where JSON arrays would not feel very natural (you'd have to use index values of the array in order to address e.g. policy entries instead of a meaningful key).

So e.g. (based in your proposal example) in order to retrieve the permissions on "features" level of "thing" of the `DEFAULT` policy entry role the HTTP API currently is:
`GET /api/2/policies/namespace:policy-name/entries/DEFAULT/resources/thing:/features`
In your proposal it would be: 
`GET /api/2/policies/namespace:policy-name/entries/0/resources/thing/1`

Not very understandable from the outside. And what happens if the order of the arrays change, e.g. because a new entry is added at the position 0? Then existing code using array identifiers will work on false assumptions.

I see your concerns, I personally don't know JMESPath and JSONata, so that didn't influence the design.

I fear using arrays as schema of Ditto's `Thing` or `Policy` entity is something we will always be skeptical about due to the fact that they would have to be addressed via array index at HTTP API level.

**Comment by dlouiscastillo** [comment]
Thanks for the quick response to my query. 

While I fully appreciate and understand your explanation about having to know and use an index values from array in an api, I'm not suggesting that you change the API. Nor am I suggesting that a developer needs to represent the data structure in code in the same manner as the API or the JSON message sent over the wire. 

All I'm suggesting is that by conforming to a keyname/value structure in JSON over the wire, it is far easier to parse and Get and Set the relevant data.

For example, If I want to set the path for a thing, I should be able to use dot syntax to do so.
policy.admin.resources.thing.path = "/features";
In this way, my intention is to set the path for the admin role for the thing to "/features";

If I want to retrieve the path, I should also be able use dot syntax to do so,
var mypath = policy.admin.resources.thing.path;

In the current schema, where there is no path property and the path info is part of the key, I can't use dot syntax'

For example,
policy.admin.resources..thing:/features = ...

Oh, but I can't use ":" and "/" in dot syntax so maybe I could try this

policy.admin.resources.['thing:/']..

we'll, while it may not look pretty, it does work as far as retrieving the data, but what if I want to set it.

policy.admin.resources['thing:/features'] = ...
That also works,  while it doesn't replace the existing path, it instead adds a second key.

In any case, this is the only API that presents this kind of problem that I have discovered in the project.

Call me a lazy developer if you like, but I've gotten use to working with JSON as keyname/value pairs, and dot syntax and I much prefer it.      
 
David

**Comment by thjaeckle** [comment]
Ah, but Ditto's "over-the wire" JSON format is the same as the HTTP API structure (which is one of the fundamental concept, e.g. in order to enable partial updates and partial queries at the HTTP API), so the JSON format is the API.

I agree that is is not very helpful in Javascript. I also like using the dot-notation wherever possible when I need to code in JS :)

Sorry that I have to state out that the format won't change any time soon - maybe for an API version "3", which we have no concrete plans about yet.

**Comment by dlouiscastillo** [comment]
Understood, I didn't expect it to change on a dime. I'm able to work around it with a little pre-processing anyway. 

It just seemed reasonable to centralize the pre-processing on server-side before the message is sent out over the wire and then pre-process it server-side when messages, partial or otherwise come back.

Then the rest of us hopefully large numbers of developers some day won't have to reinvent the wheel every time.

Cheers, 

david

**Comment by thjaeckle** [comment]
closing this as there are currently no plans to change the policies structure/API
