### ISSUE TITLE
Map Hono device connection status to Thing feature

### ISSUE THREAD

**Issue by dguggemos** [eclipse/ditto#492]
Hono sends notifications about the current connection status of a device ([Device Notifications](https://www.eclipse.org/hono/docs/concepts/device-notifications/#time-until-disconnect-notification) and [Connection Events](https://www.eclipse.org/hono/docs/concepts/connection-events/)). We want to use this information in Ditto to represent the current connection status as a Feature by providing a payload mapper for this purpose. 
Basic implementation idea:
* allow multiple mappings per connection
* result of these mappings (if any) are forwarded to concierge service in same order
* provide Java based mapping for Hono status notifications
  * if the status information is not available, no message is produced by the mapping
  * Feature ID is configurable in the mapping, default is `ConnectionStatus`
  * a vorto definition exists for the connection status feature

**Comment by glennergeerts-aloxy** [comment]
Hi, this is a very useful feature to have indeed. However, I was wondering how this would work when using something like the `Vorto Semantic Middleware` (as described here https://github.com/eclipse/vorto-examples/tree/master/vorto-hono-subscriber) sitting in between Hono and Ditto. In this setup Ditto will probably not receive these events currently. This might be fixed by adapting the Vorto middleware to forward this as well (and let Ditto take care of this as proposed here), or by moving this logic (of mapping the status information to the Feature) to the Vorto middleware. If it is the intention to add the Vorto middleware in between Hono and Ditto as a `preferred` setup for integrating these projects, I think the section option might make more sense.
What is your view on this?

**Comment by thjaeckle** [comment]
I guess both alternatives would be valid for a middleware responsible for transformation.
