### ISSUE TITLE
MQTT 5 Support

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#547]
With #487 the HiveMQTT client was introduced which supports MQTT 5 protocol. A lot of the more advanced features like header mapping and source enforcement are only supported with headers which MQTT 5 provides.

Implementation
---

Not yet implemented MQTT 3 Features

- keepAlive
- willPublish

MQTT 5 client configuration options:

- [ ] sessionExpiryInterval
- [ ] restrictions
- [x] userProperties

Sub-tasks:

- [x] Update Documentation
  - [x] Basic Concepts / Connections
  - [x] Connectivity API / MQTT 5 Protocol Binding
  - [x] Document client-specific config (e.g. `clientId`)
- [x] Implement basic MQTT 5 client based off HiveMQTT 3
  - [x] Tests
- [x] Implement MQTT 5 userProperties
  - [x] Tests
- [x] Implement Header Mapping
  - [x] Tests
- [x] Implement Source Enforcement
  - [x] Tests
- [x] Add to DefaultClientActorPropsFactory.java
  - [x] Tests
- [x] Add mqtt 5 to MqttValidator
  - [x] Tests
- [ ] Implement Mqtt5Config (and Mqtt3Config?)
  - [ ] Tests

Discussion
---

**user properties and header mapping** are the way a client may provide additional header values in MQTT 5. Additional to the user properties, there are fixed and variable properties available. I had a look at the EMQX Broker for a reference of available properties. These are among others `Correlation Data`, `Response Topic` and `Content Type`. Those can be implemented as general available headers for header mapping.

User defined properties for targets can be defined via the specific Configs map in the connections configuration.

**Source Enforcement** for the time being I have no clear idea how to implement the source enforcement. MQTT 5 provides a property `Authentication Method` together with `Authentication Data`. This does not apply for publish and other message types however. 

Question: The clientid is already extracted and some brokers enforce the client id via certificate based authentication. Is this enough to have a first source enforcement?

Additionally to this, the broker would require the ability to set user defined properties per message right? Since the user defined properties are the only headers that are valid for all message types.

**Validator and MQTT5Config?** Is it necessary to have these classes separate from mqtt3? The validator currently has a hard check for `MQTT 3.1.1` in the protocol param. Should there be just an extension for `MQTT 5` or a separate validator? What do you think?

**Comment by thjaeckle** [comment]
Hi @w4tsn 
First of all thank you for start working on the MQTT5 support, that will be a great enhancement 👍 

For your discussion points:
**user properties and header mapping**: yes, makes perfect sense using the pre-defined and user-properties for header mappings in connection sources and targets.
I guess that the HiveMQ mqtt5 client has special setters/getters for the pre-defined properties (like `Content Type`, `Correlation Data` or `Response Topic`) and that those are not duplicated in the `user properties` with e.g. keys "content-type" ...
We have a similar challenge in the Amqp10 connection - there we use the Qpid-Jms-Client which also defines methods like `setJmsCorrelationId`. There we want to just use "correlation-id" as key in a header mapping.
We solved that by "mapping" header keys to methods to be invoked on a `Message` instance, see here:
https://github.com/eclipse/ditto/blob/master/services/connectivity/messaging/src/main/java/org/eclipse/ditto/services/connectivity/messaging/amqp/AmqpPublisherActor.java#L79

We should do the same for the MQTT5 implementation, defining that header keys "correlation-id", "content-type", "reply-to" are mapped to MQTT5 `Correlation Data` , `Content Type` and `Response Topic`.
We are currently working on #540 which will solve that more elegant for AMQP 1.0 header mappings, we will get a WIP PR out so that you may use the same pattern.

**Source Enforcement**: The idea of source enforcement is to extract information towards the device identity from each consumed message (in order to ensure that the targeted thing in the Ditto Protocol message has the same identifier as the device which sent the message). Eclipse Hono for example sets the `device_id` header for each message.
I also don't see a default defined property for that in the MQTT5 properties. 
As you suggested that could however be done via user defined properties. Preferably done by the broker, yes - otherwise the device could still pretend to be another device.

What we suggest for MQTT 3 here is to use the MQTT topic as source of the device id (see also placeholder `{{ source:address }}` documented here: https://www.eclipse.org/ditto/basic-connections.html#source-enforcement
So an enforcement could look like:
```
{
  "addresses": [ "my-mqtt-root-topic/+" ],
  "authorizationContext": ["ditto:inbound-auth-subject"],
  "enforcement": {
    "input": "{{ source:address }}",
    "filters": [ "my-mqtt-root-topic/{{ thing:id }}" ]
  }
}
```
Under the assumption that a device always sends data to `my-mqtt-root-topic/<device-id>` and the broker enforces (e.g. via ACL in Mosquitto) that only that device may publish data to that topic.

I would also suggest that approach for MQTT5 - or alternatively get the broker to set a `device_id` header :)

**Validator and MQTT5Config**: The validator should be re-usable for MQTT5, yes.
