### ISSUE TITLE
1.0.0 migration script broke database

### ISSUE THREAD

**Issue by w4tsn** [eclipse/ditto#576]
After running the migration script from the [1.0.0 release notes](https://www.eclipse.org/ditto/release_notes_100.html#migration-notes) my database stopped working, or rather the ditto things service complained about 'journal_tag_index' being a duplicate on this database.

First problem I encountered was, that I had to split the script up into things and policies scripts and run them on the respective databases, since the script itself would otherwise just run on test. I suppose it's written for a one-database-for-all scenario? In the docker-compose scenario however, each service uses it's own db in the mongodb instance. That's actually the way the script of the initial commit for the script works (which is not linked in the release notes).

Overall I was quite confused on how this migration works honestly.

My setup
---

I started using ditto at version 0.8.0 and did a migration on 0.9.0. It could be that I failed in doing so correctly which caused the collections `_journal` and `_snaps` to already exist. 

I dropped `things.things_journal`, `things.things_snaps`, `policies.policies_journal` and `policies.policies_snaps` before running this migration, so the migration would work. Propably the indexes, although not shown, were/are still there? The strange thing now is, that the index `journal_tag_index` seems to exist, but is not shown when executing `_journal.getIndexes()`.

Workaround
---

In my case I removed the 'journal_tag_index' index from `things.things_journal` and `policies.policies_journal` respectively.

Implementation
---

I'm not sure yet and quite insecure if this is just a quirk in my setup or a general problem which would require a broader discussion and real solution.

**Comment by yufei-cai** [comment]
Thanks for reporting! The script is fixed in #577. Yes, dropping `journal_tag_index` should fix the issue; I forgot to create it "sparse". The script should definitely account for or at least document the case multi-database setup.

The script copies all documents in suffixed event journals and snapshot stores. To avoid wasting bandwidth transmitting most of the database, the script uses MongoDB's server-side-scripting method `mapReduce`. Since `mapReduce` produces documents in a fixed format not compatible with the persistence plugin, a follow-up aggregation step is needed to fix the document format. Input and output collection name is the same for the aggregation step so that MongoDB can optimize for disk space.
