### ISSUE TITLE
Support for GraphQL

### ISSUE THREAD

**Issue by ottlukas** [eclipse/ditto#585]
As REST is often over- and underfetching of Data. GraphQL would enable to query / CRUD specific values already from API. So GraphQL support could come in handy. This is just a question if GraphQL support has been considered and what the ideas / plans behind it could support Eclipse Ditto supporting GraphQL.

**Comment by thjaeckle** [comment]
Hi @ottlukas 

We already had a look at GraphQL.

And as Ditto does not "know"/"enforce" a data schema to the managed things (only stuff like "attributes", "features" is part of the given Ditto schema) and the user may use arbitrary JSON, with GraphQL there would be the need to always provide a GraphQL schema first prior in doing the powerful queries. That's why I personally think it's too complicated and the benefits from it are too few in order to be of value to the Ditto project.

What you describe with "over- and underfetching of Data" is already handled in Ditto quite well, see:
* [Partial updates](https://www.eclipse.org/ditto/httpapi-concepts.html#partial-updates)
* [Partial requests](https://www.eclipse.org/ditto/httpapi-concepts.html#partial-requests)
* [Partial requests with "fields" selector](https://www.eclipse.org/ditto/httpapi-concepts.html#with-field-selector)

Based on those concepts, Ditto will further improve on data retrival.
E.g. currently we are working on #561 which will make use of the "fields" selector syntax in order to include additional data when e.g. publishing change notifications via WebSocket or connections to brokers.

For what - in addition to the mentioned capabilities of partial updates/responses - do you think a GraphQL API would be helpful for Ditto?

**Comment by ottlukas** [comment]
Hi @thjaeckle 

Thank you for you response this was exactly the answer i was asking for! :)

The Partial requests is and [https://github.com/eclipse/ditto/issues/561](url) was exactly the questions I had.

So GraphQL API would as you answered not be needed and would just produce a lot of development effort which would not have more benefits compared to the existing partial request handling.

Thanky! 💯
