### ISSUE TITLE
Use Apache IoTDB as possible Backend / Datastore for Ditto

### ISSUE THREAD

**Issue by JulianFeinauer** [eclipse/ditto#592]
Hi folks,

this issue was initially raised by @ottlukas and he was asking if it could be possible to store "telemetry" data in Apache IoTDB (http://iotdb.apache.org/ / https://github.com/apache/incubator-iotdb).
I agree on that with Lukas, especially if one has features / properties that sends updates with high frequency (seconds or subsecond frequency).
I guess one could stay on MongoDB for long (as it can scale) but at what price if one is often interested, e.g. in showing the graph of a property as timeseries.

**Comment by JulianFeinauer** [comment]
I also had a quick look into the code / database "structure" in MongoDB.
It seems to me that Ditto uses event sourcing and the database which could be moved to IoTDB is the journals database.
Although I think the full functionality cannot easily migrated to IoTDB (as it stores lots of metadata) one could think about a "replication" of that collection to an IoTDB instance which is then used, e.g. for visualization in grafana or other things.
Then one could even get rid of this collection or clear it (if one keeps the snapshots) and still have full "telemetry" informtaion.

**Comment by thjaeckle** [comment]
Hi Julian.

Replacing MongoDB with IoTDB will not work, We use MongoDB as
* EventSourcing journal
* EventSourcing snapshot store
* Index for Ditto's search feature

So in order to get Ditto with minimal dependencies, a DB would have to cover all of these.
I don't see that IoTDB is a match for that as it focuses on time series.

What could make more sense is what we started discussing in #545 
Ditto currently can't deliver history for its "thing data". For that it would be very cool to build e.g. a facade to IoTDB with Ditto where Ditto still enforces authorization, API access, etc.

That could also be what you meant with "replication" of the data which would be a best practive for CQRS which we also apply e.g. for our search index.
A new "ditto-history" microservice could subscribe to `ThingEvent`s in Ditto's cluster (those are the ones you saw in the event journal collection) and for each event update all of the affected datapoints in an IoTDB instance.
It would also enabled querying the data from IoTDB making sure that only authorized users (via Ditto's policies) have access to the historical data.

Does this make sense?

**Comment by JulianFeinauer** [comment]
Good Morning @thjaeckle and thanks for the quick reply. You describe pretty detailed what I tried to describe, exactly, yes : )
On one hand one could keep dittos regular functionality and change nothing in the core (I agree its not the use case of IoTDB) but on the other hand one could get a nice representation of "property changes" as traces (with all benefits like Graphing, etc).
I would be happy to work together with you on this topic if you already have some ideas! :)

**Comment by thjaeckle** [comment]
I would suggest closing this issue in favor of #545 then .. maybe you could add your thoughts to #545 

I indeed have some ideas (also already written some done in #545 ;)), e.g. in order to use "tags" (don't know if there is an equivalent in IoTDB) in order to tag data with authorization information.
