### ISSUE TITLE
Improve websocket message queues

### ISSUE THREAD

**Issue by jokraehe** [eclipse/ditto#616]
In the current implementation a websocket session handles response correlation by putting messages, which require a response by setting the response-required header, in a list. This list is limited and elements are only removed if a response is dispatched.
Messages without response-required header are treated as if they require a response, so if one makes a mistake and forgets the header Ditto won't respond at all when the correlation list is full.

**Comment by Yannic92** [comment]
That's a good change IMHO. If someone actually want's a response he or she will notice that there isn't one coming. So the "mistake" will be found within minutes. If the user just isn't aware of the header and doesn't send responses this will lead to a hard to find issue.

However this would be a breaking change in our API. Can we introduce such a change before ditto 2.0?

**Comment by yufei-cai** [comment]
I don't think the change is an API break because the user does not get any information why or where the message stops. He will question the network transport, all the proxies in between and the websocket client before checking the back-end, which doesn't even log anything in this case (okay that was me).
