### ISSUE TITLE
Ditto tries to use deleted connections for messaging

### ISSUE THREAD

**Issue by JulianFeinauer** [eclipse/ditto#656]
What I did:
* Register Connections (mqtt) and delete them afterwards (they also had the messaging topic)
* Try to send a message to the device via HTTP

I get the response:
```
{
  "status": 404,
  "error": "connectivity:connection.notfound",
  "message": "The Connection with ID 'mqtt-example-connection-7' could not be found or requester had insufficient permissions to access it.",
  "description": "Check if the ID of your requested Connection was correct and you have sufficient permissions."
}
``` 
where the name of the connection is sometimes `mqtt-example-connection-6` and `mqtt-example-connection-7` (both existed and where deleted). It seems like this is random. 

So i have the impression that the deleted connection is still somewhere as reference and is picke by chance.

**Comment by yufei-cai** [comment]
Hi @JulianFeinauer, thanks for reporting.

The cause is a missing `UPDATE_SUBSCRIPTIONS` stage in `DeleteConnectionStrategy`. I will prepare a PR.

In the mean time, the error should disappear after the connection persistence actor stops itself. It happens 5 minutes after deletion by default. The 5m interval is configured at `ditto.connectivity.connection.activity-check.deleted-interval` in `connectivity.conf`.
