### ISSUE TITLE
Postman Collection based on API v1

### ISSUE THREAD

**Issue by demetz** [eclipse/ditto#672]
The [Ditto Postman collection](https://www.eclipse.org/ditto/httpapi-postman.html) still uses the API v1, which is now deprecated.

**Comment by yufei-cai** [comment]
Thanks for reporting!

**Comment by raujonas** [comment]
@yufei-cai I've created a postman collection for the v2 http api. Everything is tested except the "Messages" part because currently I don't know how to test it properly to be honest. So if you're still interested I would love to share it and to create a PR.

If yes, in which directory should I place the collection? Should I also add this page (https://www.eclipse.org/ditto/httpapi-postman.html) again to the docs and update it?

**Comment by thjaeckle** [comment]
Oh sh** .. I just noticed that the https://www.eclipse.org/ditto/httpapi-postman.html page is long deleted and should no longer be published (it's also not appearing in the default sidebar of the website).
However, the page is still up and at a quite old version (January 2020).

We could re-add it of course based on e.g. what @raujonas has.
We once decided to delete it as Postman is able to import the Ditto OpenAPI specification which is quite good maintained:
* https://www.eclipse.org/ditto/http-api-doc.html
* Soruce: https://www.eclipse.org/ditto/openapi/ditto-api-2.yml

What does you postman collection contain in addition, @raujonas ?

**Comment by raujonas** [comment]
> We once decided to delete it as Postman is able to import the Ditto OpenAPI specification which is quite good maintained:

I only did it because I was somehow not able to find the yml file at [https://www.eclipse.org/ditto/openapi/ditto-api-2.yml](https://www.eclipse.org/ditto/openapi/ditto-api-2.yml) and did not know how to get this file from the api doc site you've mentioned.

I think I have nothing to offer in addition then, but you can have a look at it if you want: [https://gist.github.com/raujonas/d1834f96ea72e7ccf54a094447a8f540](https://gist.github.com/raujonas/d1834f96ea72e7ccf54a094447a8f540). 
I suited it my needs, for example I use only basic auth, added only the minimal params or added variables in the paths like this {{basePath}}/things/{{thingId}}/features/{{featureId}} but that is of course only my subjective preference.

So I think importing it via your OpenAPI specification is more accurate, but maybe a link on the api doc site would be helpful if it is not obvious and I just overlooked it.

**Comment by thjaeckle** [comment]
@raujonas thanks for your offer
To be honest, I would prefer to not introduce the postman collection (again) and rely on the OpenAPI docs by importing them in Postman.
If we would add a separate Postman collection again, this would not be that actively maintained whereas the OpenAPI docs are.

We could however re-create the https://www.eclipse.org/ditto/httpapi-postman.html page describing how to import the OpenAPI available at https://www.eclipse.org/ditto/openapi/ditto-api-2.yml into Postman and which variables have to be set where.

**Comment by thjaeckle** [comment]
I deleted the https://www.eclipse.org/ditto/httpapi-postman.html for now - as it was outdated - this "resolves" this issue as Ditto now doesn't host an (outdated) Postman collection.
