### ISSUE TITLE
Support for adding arbitrary _metadata for features / properties

### ISSUE THREAD

**Issue by JulianFeinauer** [eclipse/ditto#680]
Hi all,
if considering using some kind of History API (see #545 ) it gets more and more relevant to know the timestamp of a specific value from a thing. Also in scenarios where you have no direct connection like HTTP / WS but have messaging involved like MQTT or generally Hono you can not rely that the timestamp when you receive an update message is roughly equivalent to the timestamp when it was measured. 

I thus suggest to enable explicit support for "last_modified" timestamp which could be either set explicitly in the message or implicitly with the "ingestion time" and which is then available for a possible history service and for users to see how "valid" their datasets are.

**Comment by thjaeckle** [comment]
Indeed that would be useful to have as metainformation for each property.
As we can't simply store the timestamp or any additional meta data it in the "target JSON" without modifying the user/device provided JSON structure, that would have to be stored besides the "target JSON" structure.
E.g. under a `_meta` field:
```json
{
  "thingId": "org.eclipse.ditto:thing-1",
  "policyId": "...",
  "features": {
    "lamp": {
      "properties": {
        "on": true,
        "color": {
          "r": 0,
          "g": 255,          
          "b": 255,
        }
      }
    }
  },
  "_modified": "2020-06-09T14:30:00Z",
  "_revision": 42,
  "_meta": {
    "policyId": {
      "_modified": "2020-06-09T14:00:00Z",
      "_revision": 1
    },
    "features": {
      "lamp": {
        "properties": {
          "on": {
            "_modified": "2020-06-09T14:30:00Z",
            "_revision": 42
          },
          "color": {
            "r": {
              "_modified": "2020-06-09T14:15:00Z",
              "_revision": 23
            },
            "g": {
              "_modified": "2020-06-09T14:15:00Z",
              "_revision": 23
            },
            "b": {
              "_modified": "2020-06-09T14:15:00Z",
              "_revision": 23
            }
          }
        }
      }
    }
  }
}
```

Basically each "leaf" in the JSON gets an JsonObject containing additional meta information.
That could also be aggregated upwards, so in the provided example above you would know that the "lamp" feature is also of revision `42` last modified at the timestamp `14:30`.

I would also want to see the "revision" as meta information at a property level, so that you can e.g. see (like in Subversion) which revision a part of the subtree of a Thing or even a single property has.
But that may be a topic for another issue. :)

**Comment by JulianFeinauer** [comment]
Hey @thjaeckle welcome back : )
I would try to take care of the implementation if you generally agree. Do you have a pointer for me where to look at as start?
And I think we should also try to differentiate two things: date of last modification and timestamp of the value (which may be the same but maybe totally different also)

**Comment by thjaeckle** [comment]
> I would try to take care of the implementation if you generally agree. Do you have a pointer for me where to look at as start?
Cool, I think this would a great addition to Ditto without breaking existing functionality.

The best way I can think of is to enhance the [AbstractThingEventStrategy](https://github.com/eclipse/ditto/blob/master/services/things/persistence/src/main/java/org/eclipse/ditto/services/things/persistence/actors/strategies/events/AbstractThingEventStrategy.java#L49) to - in addition to the already set "setRevision(long)" and "setModified(Instant)" also invoke something like `setMetadata(JsonPointer, Metadata)`.
At the mentioned spot you have the `ThingEvent` containing which `JsonPointer getResourcePath()` was affected (which you need in order to set the `Metadata` information on the right JSON "level"), containing the `Optional<JsonValue> getEntity()` and also containing `DittoHeaders getDittoHeaders()` (which might e.g. include the "actual device modification timestamp" - propsal: `"_issuedAt"` - which could be a different one).

Having found that place, additional things are needed to be implemented:
* the `ThingBuilder`s (`ThingBuilder.FromCopy` and `ThingBuilder.FromScratch`) need to be enhanced by setting the new additional "meta" information
* we would need a new type (Interface + immutable implementation) e.g. `Metadata` in package `org.eclipse.ditto.model.base.entity`
** the `Metadata` interface would define (with an inner subclass for the `JsonFields`) which metadata information can be expected and which Json+Java type this metadata has - for example please have a look at `Thing.JsonFields`
* the `org.eclipse.ditto.model.base.entity.Entity` needs to be enhanced by a getter and setter for this "Metadata" instance (I would add that on `Entity` rather than on `Thing` so that the `Policy` also being an `Entity` might also benefit from that)
* the `Thing.JsonFields` needs to be enhanced by a new constant for the `"_metadata"` JSON field
* the `ImmutableThing`'s `JsonObject toJson(JsonSchemaVersion, Predicate<JsonField>)` needs to write the new "_meta" field when serializing a Thing Java object to JSON
* the `ImmutableThingFromCopyBuilder of(JsonObject)` needs to read the "_meta" field when deserializing to a Thing Java object again from JSON
* I also think we need to enhance the `DittoHeaderDefinition` with a special header specifying the modification timestamp coming from a device
** then, also `DittoHeaders`, `DittoHeadersBuilder` and the implementations need to be adjusted accordingly (incl. JSON serialization)

Do you need that new meta information also in each Event emitted via Ditto (I guess so)?
Then the `org.eclipse.ditto.signals.events.base.Event` would need to be enhanced with that "Metadata" information as well, as well as serialization to JSON and deserialization back to Java objects in the implementations responsible for JSON serialization (e.g. in `AbstractThingEvent`).

Those are the first things popping into my mind.
That might seem a lot but I think this is a rather low hanging fruit - the main effort is in enhancing the Ditto "model" around Entity/Thing by adding the `Metadata` type and to enhance the "Event" as well.

Making the "_metadata" field in the `Thing.JsonFields` a `FieldType.SPECIAL, FieldType.HIDDEN` field (like e.g. also `"_modified"`, the field will not by default be returned when retrieving a Thing via the HTTP API - it should work automatically then to provide a "fields" query in order to retrieve that information, e.g.:
`GET /api/2/things/org.eclipse.ditto:thing-1?fields=policyId,features,_revision,_metadata`

> And I think we should also try to differentiate two things: date of last modification and timestamp of the value (which may be the same but maybe totally different also)
Yes, maybe we can provide a "_modified" field and in addition an optional "_issuedAt" field.
If both are the same, it is sufficient to only set the "_modified" - if they differ, both values are set in the created instance of `Metadata`.
The `Optional<Instant> getIssuedAt()` in `Metadata` interface would indicate that by using an `Optional` return type.

What do you think?

**Comment by JulianFeinauer** [comment]
Hi all, I had a discussion with @thjaeckle about whether we should send the information "issuedAt" in a Ditto Header or allow the user to write it through the Thing object himself. Currently there is the convention that "_xxx" fields are write protected and read only for the user. I move this discussion here that everybody can participate.

**Comment by thjaeckle** [comment]
I would like to keep the pattern that all JSON fields starting with `_` are 
* hidden by default (e.g. when doing a GET request)
* and are read only by default (and always set by Ditto only)

Having thought about it a while I see this variant which might ease things up:
* keep `_metadata` and as a result make everything in it read only
* have specific metadata fields which Ditto automatically sets (currently: `_revision` and `_modified`)
* define a prefix for header fields which should be added by Ditto into the _metadata section, e.g.: `ditto-metadata:`
   * by default, a set metadata value is applied to all JSON leaves affected by a modifying command, e.g.: `ditto-metadata:issuedAt`
   * similar to policy resources, the ditto-metadata could contain an optional JsonPointer of which property to address the metadata value to if a metadata value should not be applied to all affected JSON fields of a processed command


Example headers when modifying a complete thing (`ModifyThing` command - [example](https://www.eclipse.org/ditto/protocol-examples-modifything.html#modifything)):
```json
{
  "topic": "org.eclipse.ditto/thing-1/things/twin/commands/modify",
  "headers": {
    "ditto-metadata:issuedAt": "2020-06-09T14:29:00Z",
    "ditto-metadata:/features/lamp/properties/color/r/issuedAt": "2020-06-09T14:14:00Z",
    "ditto-metadata:/features/lamp/properties/color/g/issuedAt": "2020-06-09T14:14:00Z",
    "ditto-metadata:/features/lamp/properties/color/b/issuedAt": "2020-06-09T14:14:00Z"
  },
  "path": "/",
  "value": {
    "features": {
      "lamp": {
        "properties": {
          "on": false,
          "color": {
            "r": 255,
            "g": 255,
            "b": 0
          }
        }
      }
    }
  }
}
```

Another example for modifying the feature properties of a thing (`ModifyFeatureProperties` command - [example](https://www.eclipse.org/ditto/protocol-examples-modifyproperties.html#modifyfeatureproperties):
```json
{
  "topic": "org.eclipse.ditto/thing-1/things/twin/commands/modify",
  "headers": {
    "ditto-metadata:issuedAt": "2020-06-09T14:29:00Z",
    "ditto-metadata:/color/r/issuedAt": "2020-06-09T14:14:00Z",
    "ditto-metadata:/color/g/issuedAt": "2020-06-09T14:14:00Z",
    "ditto-metadata:/color/b/issuedAt": "2020-06-09T14:14:00Z"
  },
  "path": "/features/lamp/properties",
  "value": {
    "on": false,
    "color": {
      "r": 255,
      "g": 255,
      "b": 0
    }
  }
}
```

The resulting JSON for both of the above commands would e.g. look like:
```json
{
  "thingId": "org.eclipse.ditto:thing-1",
  "policyId": "...",
  "features": {
    "lamp": {
      "properties": {
        "on": true,
        "color": {
          "r": 0,
          "g": 255,          
          "b": 255,
        }
      }
    }
  },
  "_modified": "2020-06-09T14:30:00Z",
  "_revision": 42,
  "_metadata": {
    "policyId": {
      "_modified": "2020-06-09T14:00:00Z",
      "_revision": 1
    },
    "features": {
      "lamp": {
        "properties": {
          "on": {
            "_modified": "2020-06-09T14:30:00Z",
            "_revision": 42,
            "issuedAt": "2020-06-09T14:29:00Z"
          },
          "color": {
            "r": {
              "_modified": "2020-06-09T14:30:00Z",
              "_revision": 42,
              "issuedAt": "2020-06-09T14:14:00Z"
            },
            "g": {
              "_modified": "2020-06-09T14:30:00Z",
              "_revision": 42,
              "issuedAt": "2020-06-09T14:14:00Z"
            },
            "b": {
              "_modified": "2020-06-09T14:30:00Z",
              "_revision": 42,
              "issuedAt": "2020-06-09T14:14:00Z"
            }
          }
        }
      }
    }
  }
}
```

I think that would support the principle: "Make simple things simple, make complex things possible.
* the "simple things": by adding a single header, e.g. `"ditto-metadata:issuedAt": "2020-06-09T14:29:00Z"` all affected JSON keys in the command will get that same metadata information
* the "complex things": if that is not sufficient, a header for each differing metadata field can be added

**Comment by JulianFeinauer** [comment]
Hey @thjaeckle I really like your idea as it makes it easy to add other metadata values and is not fixed add "add timestamps". So I will try to go on like that. Thanks!

**Comment by jufickel-b** [comment]
The suggested header syntax has one major drawback.
Assuming a command modifies a complete thing (`ModifyThing` command) like the following:
```
{
  "topic": "org.eclipse.ditto/thing-1/things/twin/commands/modify",
  "headers": {
    "ditto-metadata:issuedAt": "2020-06-09T14:29:00Z",
    ...
  },
  "path": "/",
  "value": {
    "features": {
      "lamp": {
        "properties": {
          "on": false,
          "color": {
            "r": 255,
            "g": 255,
            "b": 0
          }
        }
      }
    }
  }
}
```
Then the value of "issuedAt" would be applied to all feature properties, i. e. `on`, `r`, `g`, `b`.
This way it is impossible to set a metadata value exclusively at the root level (`/`), i. e. the thing itself.

How about a syntax which allows to determine the level more specifically?
**Example one:**
```
{
  "topic": "org.eclipse.ditto/thing-1/things/twin/commands/modify",
  "headers": {
    "ditto-metadata:issuedAt": "2020-06-09T14:29:00Z",
    ...
  },
  "path": "/",
  "value": {
    "features": {
      "lamp": {
        "properties": {
          "on": false,
          "color": {
            "r": 255,
            "g": 255,
            "b": 0
          }
        }
      }
    }
  }
}
```
Example one is interpreted in a way to set the value of "issuedAt" only at the root level (path `/`).

**Example two:**
```
{
  "topic": "org.eclipse.ditto/thing-1/things/twin/commands/modify",
  "headers": {
    "ditto-metadata:*/issuedAt": "2020-06-09T14:29:00Z",
    ...
  },
  "path": "/",
  "value": {
    "features": {
      "lamp": {
        "properties": {
          "on": false,
          "color": {
            "r": 255,
            "g": 255,
            "b": 0
          }
        }
      }
    }
  }
}
```
In example two the asterisk implies that the value of "issuedAt" should be applied to all the affected JSON leaves, in this case `on`, `r`, `g` and `b`.

**Comment by thjaeckle** [comment]
> How about a syntax which allows to determine the level more specifically?

I like that concept 👍

**Comment by JulianFeinauer** [comment]
@jufickel-b thanks, this is a neat idea. From an application perspective I would always prefer the second example as it saves some algorithmic complexity. But just to assure.. in both cases the algorithm would hold and stay consistend 

```
check if there is an issuedAt at your node
if not, go to parent and repeat until you found one
```

Or can there be a sequence of messages that leads to a situation where aboves algorithm would yield a wrong response? I'm not sure ATM.

**Comment by jufickel-b** [comment]
@JulianFeinauer I think so, too. I cannot think of a message sequence which disturbs the algorithm.

**Comment by jufickel-b** [comment]
With commit [74af61f](https://github.com/JulianFeinauer/ditto/commit/74af61fc320f52e3271a13b1735b92364bfe6cf5) an implementation of my suggestion dated 2020-07-30 exists.

Tests showed however, that there is a problem: HTTP headers are not allowed to contain slashes or colons. Thus the syntax of the metadata header should be changed.

I already had a discussion with @thjaeckle regarding this issue. We think that it would be best to change the syntax of metadata header as follows:

Header name: `metadata` as the prefix `ditto-` implies that it cannot be set externally but only internally by Ditto itself.
Header value: `PATH=VALUE` where `PATH` is either a regular JSON Pointer or a "wildcard path" like for example `/*/issuedAt`. `VALUE` is a valid JSON value. Multiple metadata key-value pairs are separated by a comma `,`.

A HTTP header for setting metadata could look as follows – the leading slash (`/`) of the paths is optional:

    metadata: /*/issuedAt="2020-06-09T14:29:00Z",/color/r/someCounter=23

This approach has the advantage that `metadata` could become a well-known `DittoHeaderDefinition` as it is no longer just a prefix.

@JulianFeinauer what do you think about this topic?

**Comment by JulianFeinauer** [comment]
Thanks for all the effort you put into the topic @jufickel-b and @thjaeckle !
The suggestion is fine for me although we could probably look for a well known format to transport the list of metadata like JSON to make it easier (from an application perspective) to parse and serialize the information.

WDYT?

**Comment by jufickel-b** [comment]
We discussed this, too and this is also fine. If the header value was a JSON object the example would look like

    metadata: {"/*/issuedAt":"2020-06-09T14:29:00Z","/color/r/someCounter":23}

The advantage, like you already mentioned, is a well-known format (JSON) which makes it easier for applications to handle.
A possible drawback could be that the header value could be confused with the effective `Metadata` object of the thing (_metadata).

Should we go with JSON?

**Comment by JulianFeinauer** [comment]
From a users perspective definetly JSON but I get your point.
But I think there are few alternatives if we have multiple informations in one header fields payload, or?

**Comment by jufickel-b** [comment]
Yes, indeed. So JSON it is :-)

**Comment by Yannic92** [comment]
I think we could run into problems with the single JSON-Object as Metadata value.
Our JSON parsing will parse this meta data : 
`meta-data: {"/features/lamp/properties/color/r":{"issuedAt":someTimestamp, "issuedBy":{"name": "me", "mail":"me@mail.com"}}}`

To the following JSON Object. After this parsing we can't get the initial path `/features/lamp/properties/color/r` anymore
```
{
  "features": {
    "lamp": {
      "properties": {
        "color": {
          "r": {
            "issuedAt": "someTimeStamp",
            "issuedBy": {
              "name": "me",
              "mail": "me@mail.com"
            }
          }
        }
      }
    }
  }
}
```

Therefore I suggest a format like this:

```
meta-data: [{
  "path" : "/features/lamp/properties/color/r":
  "value" : {"issuedAt":someTimestamp, "issuedBy":{"name": "me", "mail":"me@mail.com"}}
}]
```

**Comment by jufickel-b** [comment]
@Yannic92 this is exactly the behaviour I experienced while playing around.
Your suggestion seems to be a reasonable solution.

**Comment by jufickel-b** [comment]
With commit https://github.com/JulianFeinauer/ditto/commit/97229c2c61416e33bc2dcd9f20ccfd909c39546d we have a working state for setting metadata via headers.

A valid HTTP header of this implementation looks like for example (formatted for better readability)
```
metadata: [
  {
    "key":"/features/lamp/properties/color/r",
    "value":{"issuedAt":someTimestamp,"issuedBy":{"name":"me","mail":"me@mail.com"}}
  },
  {
    "key":"*/",
    "value":"bar"
  }
]
```

I wonder how one could get rid of unused metadata, as headers only allow to set metadata. An already working solution could be to set the value to the `null` literal at an appropriate level. What do you think?

Still missing is proper documentation of the feature in `ditto-documentation`. @JulianFeinauer do you want to add some?

**Comment by JulianFeinauer** [comment]
First, thanks for your strong support @jufickel-b and @thjaeckle . I will add documentation and I would be fine with deleting them via "setting" them to null.

**Comment by thjaeckle** [comment]
I adjusted the title of the issue as this turned out to be a more generic approach (which I highly appreciate :+1:)
