### ISSUE TITLE
Sever Sent Event ( question)

### ISSUE THREAD

**Issue by Geonjae-Joo** [eclipse/ditto#814]
I try to do SSE.
No idea what is wrong here. anyone help me out please? 
I deployed with helm. It seems there's a problem with CORS but I dont know how to fix it.

![image](https://user-images.githubusercontent.com/62494715/93860192-a98f0480-fcf9-11ea-8371-e5676ae5ae64.png)

![image](https://user-images.githubusercontent.com/62494715/93860903-aea08380-fcfa-11ea-943f-7eac56e2b831.png)

![image](https://user-images.githubusercontent.com/62494715/93860377-fffc4300-fcf9-11ea-939f-0ce28fcf4748.png)

**Comment by thjaeckle** [comment]
As the chrome error message states:
It seems that it is not allowed to return `Access-Control-Allow-Origin: *` in combination with using an `EventSource` containing `withCredentials: true`.

Ditto's `CorsEnablingDirective` sets this wildcard cross-origin-header.
I suggest that you disable the Ditto-built-in CORS header addition by configuring the gateway's env var `ENABLE_CORS` (see https://github.com/eclipse/ditto/blob/master/services/gateway/starter/src/main/resources/gateway.conf#L30 ) to false and to add the CORS headers e.g. in an nginx in front of Ditto where you don't set the wildcard `*` but use the requests.

In nginx you can do it like in this example: https://gist.github.com/alexjs/4165271

That uses the `$http_origin` to put into the `Access-Control-Allow-Origin` instead of the wildcard:
```
...
add_header 'Access-Control-Allow-Origin' "$http_origin";
add_header 'Access-Control-Allow-Credentials' 'true';
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
...
```

**Comment by thjaeckle** [comment]
Will be improved by PR #816 
The suggested behavior (which can also be done in nginx) will then be done by Ditto itself.
