### ISSUE TITLE
[Discussion] The road to Ditto 2.0 with some breaking changes on the way

### ISSUE THREAD

**Issue by Yannic92** [eclipse/ditto#978]
As we plan to release Ditto 2.0 in the near future (March/April 2021), it's time to discuss some breaking changes helping the Ditto core team in the future development (reducing maintenance of e.g. already `@Deprecated` marked APIs) but also keep an eye on the effort that would be required by our users to migrate from Ditto 1.x to Ditto 2.x.

**Comment by thjaeckle** [comment]
Here is what we currently foresee as "breaking changes" regarding our "API compatibility"/semantic versioning definition in https://github.com/eclipse/ditto/blob/master/documentation/src/main/resources/architecture/DADR-0005-semantic-versioning.md#api-compatibility

We mainly focus on binary incompatible changes to Ditto's model classes - the HTTP APIs (in API version `2`) are not affected and are still compatible. API version `1` will be dropped as we already deprecated API version `1` some time ago.

---

## 1. remove `setDittoHeaders(DittoHeaders)` from `WithDittoHeaders`
Not every class implementing `WithDittoHeaders` should also be capable of setting `DittoHeaders`. Extract a new interface for setting `DittoHeaders`.

## 2. Rework default connection behavior of Ditto Java client
By default a newly created Ditto client shall not connect itself automatically, but only when a `connect()` method is explicitly invoked. As this requires a breaking API change, this is listed here.

## 3. Make `AbstractDittoHeaders` implement `Map<String,String>`
..

## 4. Java Client API handlers should return `CompletionStage` instead of `CompletableFuture`
In Ditto Java Client 1.x all APIs return a `CompletableFuture`. That is bad as the Ditto client user may complete this `CompletableFuture` by himself which could break things in the client.  
Therefore all APIs formerly returned `CompletableFuture` will return a `CompletionStage` instead - on this the Ditto client user may still call `.toCompletableFuture()` in order to get a "new" CompletableFuture.

## 5. Make `DittoRuntimeException` abstract
We don't want to instantiate `DittoRuntimeException` itself, but only concrete implementation with a better context about the exception.

## 6. Remove dependency of placeholders model on all signals
In order to get some dependency 

## 7. Move live signals to Ditto Java client
The `ditto-signals-*-live` modules are only used in the Java client, so move it there.

## 8. Remove API 1 from models, signals, routes
API 1 (with the "ACL" based authorization) will be completely removed, both from the codebase as well as from the HTTP endpoints.

## 9. Fix `EntityId`+`WithId` and remove from `Signal` interface
Not every signal actually has a `EntityId`, but `Signal` extends `WithId` -> fix that.

## 10. Enforce Non-nullable in `PolicyResponse`s
A really small one ..

## 11. Remove all APIs marked with `@Deprecated`
Most of API 1 APIs are already marked as `@Deprecated` in the Ditto codebased, but also other methods/classes for which we already have an alternative which should be used.
Delete all of them.

## 12. Remove all remaining raw types where generics should be used
Pull through generics magic.

## 13. Re-structure Ditto's maven modules + packages
The Maven modules of Ditto are often defined technically and not feature wise. In order to fix that a lot of moving/consolidation of modules and packages is required.

---

We'll add more text to the headings, just wanted to lay out a first (rough) direction of the work on our plate for Ditto 2.0.

What is important to note: We do aim to provide minimal impact on updating a Ditto 1.5.x installation to a Ditto 2.0.0 installation - there should even be no migration effort at all if all happens as planned.

---

We ask you - our community - if you have any concerns/objections on our road towards the breaking changes Ditto 2.0.0 to ask your questions and raise your concerns here.

**Comment by jufickel-b** [comment]
I noticed a thing that annoys me a bit. Interface `Event` defines `getRevision()` and `setRevision()`. However, not each event even supports a revision number.

Some always return `0L` for getRevision and `this` for setRevision. My suggestion is to move this two methods into a "mixin" interface called `WithRevision` and let only events with an actual revision number implement it. Btw. Ditto has a type called `Revision`, why not use this instead of a `long`?

**Comment by thjaeckle** [comment]
@jufickel-b which `Event`s are that?
Because IMO no `Event` (Ditto uses to do the "event sourcing" pattern *with* persisting the event before optionally publishing it to the cluster) should have no revision.
So those entities are probably not `Event`s at all but another (new) type?

**Comment by jufickel-b** [comment]
For example `org.eclipse.ditto.signals.events.connectivity.ConnectivityEvent`. Its default implementation even throws an `UnsupportedOperationException` for both methods.

**Comment by thjaeckle** [comment]
I don't see why `ConnectivityEvent` should throw an `UnsupportedOperationException` - we should add the revision here as those events are "event sourcing" compatible.
For the `setRevision(long)` I currently don't see any non-test usage - so that method could even be removed, can't it?

**Comment by jufickel-b** [comment]
I, too, see no reason for having `setRevision(long)`.
Regarding `ConnectivityEvent`. Is the current default implementation faulty, then? If so, then I think this should be fixed with Ditto 2.0.

**Comment by thjaeckle** [comment]
> Regarding `ConnectivityEvent`. Is the current default implementation faulty, then? If so, then I think this should be fixed with Ditto 2.0.

Yes, I think so too.
